import sarab from "./assets/images/sara-b.png";

export const servicesData = [
  {
    id: 1,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 2,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 3,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 4,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 5,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 6,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 7,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 8,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 9,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 10,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 11,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 12,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 13,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 14,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 15,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 16,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 17,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 18,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 19,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
  {
    id: 20,
    title: "Pretty Films",
    rating: 4.8,
    reviews: 102,
    location: "Washington DC, DC",
    description:
      "Unlock Your Free Ultimate Wedding Video Upgrade – Exclusive for WEDDINGWIRE Couples! As a special gift for WeddingWire couples, we're offering our Ultimate Wedding Upgrade – that's $1200 worth of extra bonuses added to our video packages, at no additional cost. No catch, just added value for your...",
    features: ["Drone Footage", "Multi. Locations", "Multi. Cameras"],
    price: 2000,
    images: [sarab, sarab, sarab],
  },
];
